/*
    SoccerStore V2 schema extension draft.
    This script is additive to reduce migration risk from legacy EDMX.
*/

CREATE TABLE VAITRO (
    MAVT VARCHAR(20) NOT NULL PRIMARY KEY,
    TENVAITRO NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE KHACHHANG_VAITRO (
    MAKH VARCHAR(20) NOT NULL,
    MAVT VARCHAR(20) NOT NULL,
    NGAYGAN DATETIME NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (MAKH, MAVT),
    CONSTRAINT FK_KHACHHANG_VAITRO_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_KHACHHANG_VAITRO_VAITRO FOREIGN KEY (MAVT) REFERENCES VAITRO(MAVT)
);

CREATE TABLE TRANGTHAI_DONHANG (
    MATT VARCHAR(20) NOT NULL PRIMARY KEY,
    TENTRANGTHAI NVARCHAR(100) NOT NULL UNIQUE,
    THUTU INT NOT NULL
);

CREATE TABLE HOADON_TRANGTHAI (
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    MAHD VARCHAR(20) NOT NULL,
    MATT VARCHAR(20) NOT NULL,
    GHICHU NVARCHAR(500) NULL,
    NGAYCAPNHAT DATETIME NOT NULL DEFAULT GETDATE(),
    NGUOICAPNHAT VARCHAR(20) NULL,
    CONSTRAINT FK_HOADON_TRANGTHAI_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_HOADON_TRANGTHAI_TRANGTHAI FOREIGN KEY (MATT) REFERENCES TRANGTHAI_DONHANG(MATT)
);

CREATE TABLE PHUONGTHUC_THANHTOAN (
    MAPTTT VARCHAR(20) NOT NULL PRIMARY KEY,
    TENPHUONGTHUC NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE THANHTOAN (
    MATTTOAN VARCHAR(20) NOT NULL PRIMARY KEY,
    MAHD VARCHAR(20) NOT NULL,
    MAPTTT VARCHAR(20) NOT NULL,
    SOTIEN DECIMAL(18,2) NOT NULL,
    TRANGTHAI NVARCHAR(50) NOT NULL,
    MAGIAODICH VARCHAR(100) NULL,
    NGAYTAO DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_THANHTOAN_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_THANHTOAN_PTTT FOREIGN KEY (MAPTTT) REFERENCES PHUONGTHUC_THANHTOAN(MAPTTT)
);

CREATE TABLE NHATKY_TONKHO (
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    MASP VARCHAR(20) NOT NULL,
    MAHD VARCHAR(20) NULL,
    SOLUONGTHAYDOI INT NOT NULL,
    LOAIBIEN_DONG NVARCHAR(50) NOT NULL,
    GHICHU NVARCHAR(500) NULL,
    NGAYTAO DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_NHATKY_TONKHO_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT FK_NHATKY_TONKHO_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);

CREATE INDEX IX_HOADON_TRANGTHAI_MAHD ON HOADON_TRANGTHAI(MAHD);
CREATE INDEX IX_THANHTOAN_MAHD ON THANHTOAN(MAHD);
CREATE INDEX IX_NHATKY_TONKHO_MASP ON NHATKY_TONKHO(MASP);

INSERT INTO VAITRO (MAVT, TENVAITRO) VALUES ('R_ADMIN', N'Admin');
INSERT INTO VAITRO (MAVT, TENVAITRO) VALUES ('R_USER', N'User');

INSERT INTO TRANGTHAI_DONHANG (MATT, TENTRANGTHAI, THUTU) VALUES ('OS_NEW', N'Mới tạo', 1);
INSERT INTO TRANGTHAI_DONHANG (MATT, TENTRANGTHAI, THUTU) VALUES ('OS_CONFIRMED', N'Đã xác nhận', 2);
INSERT INTO TRANGTHAI_DONHANG (MATT, TENTRANGTHAI, THUTU) VALUES ('OS_SHIPPING', N'Đang giao', 3);
INSERT INTO TRANGTHAI_DONHANG (MATT, TENTRANGTHAI, THUTU) VALUES ('OS_DONE', N'Hoàn tất', 4);
INSERT INTO TRANGTHAI_DONHANG (MATT, TENTRANGTHAI, THUTU) VALUES ('OS_CANCELLED', N'Đã hủy', 5);

INSERT INTO PHUONGTHUC_THANHTOAN (MAPTTT, TENPHUONGTHUC) VALUES ('PM_COD', N'Thanh toán khi nhận hàng');
