//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOCCERSTOREEntities : DbContext
    {
        public SOCCERSTOREEntities()
            : base("name=SOCCERSTOREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public DbSet<GIOHANG> GIOHANGs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<HOADON_TRANGTHAI> HOADON_TRANGTHAI { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<KHACHHANG_VAITRO> KHACHHANG_VAITRO { get; set; }
        public DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public DbSet<LOAISP> LOAISPs { get; set; }
        public DbSet<NHATKY_TONKHO> NHATKY_TONKHO { get; set; }
        public DbSet<PHUONGTHUC_THANHTOAN> PHUONGTHUC_THANHTOAN { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<SANPHAM_SIZE> SANPHAM_SIZE { get; set; }
        public DbSet<SANPHAMNOIBAT> SANPHAMNOIBATs { get; set; }
        public DbSet<SIZE> SIZEs { get; set; }
        public DbSet<THANHTOAN> THANHTOANs { get; set; }
        public DbSet<THUONGHIEU> THUONGHIEUx { get; set; }
        public DbSet<TRANGTHAI_DONHANG> TRANGTHAI_DONHANG { get; set; }
        public DbSet<VAITRO> VAITROes { get; set; }
    }
}
