//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_TRANGTHAI
    {
        public long ID { get; set; }
        public string MAHD { get; set; }
        public string MATT { get; set; }
        public string GHICHU { get; set; }
        public System.DateTime NGAYCAPNHAT { get; set; }
        public string NGUOICAPNHAT { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual TRANGTHAI_DONHANG TRANGTHAI_DONHANG { get; set; }
    }
}
