//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.HOADON_TRANGTHAI = new HashSet<HOADON_TRANGTHAI>();
            this.NHATKY_TONKHO = new HashSet<NHATKY_TONKHO>();
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYHENGIAO { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string DIACHI { get; set; }
        public string GHICHU { get; set; }
        public string MAKH { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual ICollection<HOADON_TRANGTHAI> HOADON_TRANGTHAI { get; set; }
        public virtual ICollection<NHATKY_TONKHO> NHATKY_TONKHO { get; set; }
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
    }
}
