//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.HOADONs = new HashSet<HOADON>();
            this.KHACHHANG_VAITRO = new HashSet<KHACHHANG_VAITRO>();
        }
    
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string SODIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD_KH { get; set; }
        public string ROLES { get; set; }
    
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<KHACHHANG_VAITRO> KHACHHANG_VAITRO { get; set; }
    }
}
