//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG_VAITRO
    {
        public string MAKH { get; set; }
        public string MAVT { get; set; }
        public System.DateTime NGAYGAN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
