//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
            this.SANPHAMs1 = new HashSet<SANPHAM>();
        }
    
        public string MAKM { get; set; }
        public string TENKM { get; set; }
        public Nullable<int> PHANTRAMGIAM { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs1 { get; set; }
    }
}
