//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAISP
    {
        public LOAISP()
        {
            this.LOAISP1 = new HashSet<LOAISP>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public string MAL { get; set; }
        public string TENL { get; set; }
        public string MAL_CHA { get; set; }
    
        public virtual ICollection<LOAISP> LOAISP1 { get; set; }
        public virtual LOAISP LOAISP2 { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
