//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHATKY_TONKHO
    {
        public long ID { get; set; }
        public string MASP { get; set; }
        public string MAHD { get; set; }
        public int SOLUONGTHAYDOI { get; set; }
        public string LOAIBIEN_DONG { get; set; }
        public string GHICHU { get; set; }
        public System.DateTime NGAYTAO { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
