//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUONGTHUC_THANHTOAN
    {
        public PHUONGTHUC_THANHTOAN()
        {
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public string MAPTTT { get; set; }
        public string TENPHUONGTHUC { get; set; }
    
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
    }
}
