//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.NHATKY_TONKHO = new HashSet<NHATKY_TONKHO>();
            this.SANPHAM_SIZE = new HashSet<SANPHAM_SIZE>();
            this.SANPHAMNOIBATs = new HashSet<SANPHAMNOIBAT>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string MOTA { get; set; }
        public string MATH { get; set; }
        public string MAL { get; set; }
        public string MAKM { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual ICollection<NHATKY_TONKHO> NHATKY_TONKHO { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        public virtual ICollection<SANPHAM_SIZE> SANPHAM_SIZE { get; set; }
        public virtual ICollection<SANPHAMNOIBAT> SANPHAMNOIBATs { get; set; }
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
    }
}
