//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIZE
    {
        public SIZE()
        {
            this.SANPHAM_SIZE = new HashSet<SANPHAM_SIZE>();
        }
    
        public string MASIZE { get; set; }
        public Nullable<int> SOSIZE { get; set; }
    
        public virtual ICollection<SANPHAM_SIZE> SANPHAM_SIZE { get; set; }
    }
}
