//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string MATTTOAN { get; set; }
        public string MAHD { get; set; }
        public string MAPTTT { get; set; }
        public decimal SOTIEN { get; set; }
        public string TRANGTHAI { get; set; }
        public string MAGIAODICH { get; set; }
        public System.DateTime NGAYTAO { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual PHUONGTHUC_THANHTOAN PHUONGTHUC_THANHTOAN { get; set; }
    }
}
