//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAI_DONHANG
    {
        public TRANGTHAI_DONHANG()
        {
            this.HOADON_TRANGTHAI = new HashSet<HOADON_TRANGTHAI>();
        }
    
        public string MATT { get; set; }
        public string TENTRANGTHAI { get; set; }
        public int THUTU { get; set; }
    
        public virtual ICollection<HOADON_TRANGTHAI> HOADON_TRANGTHAI { get; set; }
    }
}
