//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAITRO
    {
        public VAITRO()
        {
            this.KHACHHANG_VAITRO = new HashSet<KHACHHANG_VAITRO>();
        }
    
        public string MAVT { get; set; }
        public string TENVAITRO { get; set; }
    
        public virtual ICollection<KHACHHANG_VAITRO> KHACHHANG_VAITRO { get; set; }
    }
}
